name: shorebird_batch_patch_cli
description: Automatically apply patches to relevant releases.
version: 1.0.0
repository: https://github.com/josiahsrc/shorebird-batch-patch.git
publish_to: "none"

environment:
  sdk: ^3.3.1

dependencies:
  args:
  io:
  mason_logger:
  shorebird_code_push_protocol:
    git:
      url: git@github.com:shorebirdtech/shorebird.git
      path: packages/shorebird_code_push_protocol
  scoped:
    git:
      url: git@github.com:shorebirdtech/shorebird.git
      path: packages/scoped
  cli_util:
  shorebird_cli:
    git:
      url: git@github.com:shorebirdtech/shorebird.git
      path: packages/shorebird_cli
  platform:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependency_overrides:
  shorebird_code_push_protocol:
    git:
      url: git@github.com:shorebirdtech/shorebird.git
      path: packages/shorebird_code_push_protocol
  scoped:
    git:
      url: git@github.com:shorebirdtech/shorebird.git
      path: packages/scoped
