name: shorebird_batch_patch_cli
description: Automatically apply patches to relevant releases.
version: 1.0.0
repository: https://github.com/josiahsrc/shorebird-batch-patch.git
publish_to: 'none'

environment:
  sdk: ^3.3.1

dependencies:
  args: ^2.4.2
  io: ^1.0.4
  mason_logger: ^0.2.12
  shorebird_code_push_protocol:
    git:
      url: git@github.com:shorebirdtech/shorebird.git
      path: packages/shorebird_code_push_protocol

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
